### ISSUE TITLE
[nine] rendering problem 3DMark03

### ISSUE THREAD

**Issue by leipero** [iXit/Mesa-3D#271]
This is on radeon driver, everything seems fine, but with nine it looks like lighting is missing, this is a problem since I've started testing/using nine (before Mesa 13.x), now on mesa 17.0.0.-2 (Arch).

Nine:
![02](https://cloud.githubusercontent.com/assets/21347343/23371471/89c7bdfc-fd18-11e6-995c-e3f174744196.png)

Wine-CSMT:
![01](https://cloud.githubusercontent.com/assets/21347343/23371505/9478d4de-fd18-11e6-8607-0f3f9927c045.png)

**Comment by axeldavy** [comment]
which graphic card ?

**Comment by leipero** [comment]
It's old radeon HD 6770, just tought i should report it since it is render problem, and I assume same will happen on some other GPU's (obviously HD 5770 also, since it is basically the same GPU).

**Comment by axeldavy** [comment]
It's possible this is fixed with mesa master. Somehow I have trouble testing because it won't compile.

**Comment by leipero** [comment]
I will test it as soon as possible and report back, last time I've compiled mesa for testing i had tons of problems reverting back (because some dependencies i can't recall now), eventually resulting in re-doing whole system, so i have to do it on separate partition. Will report it ~24h.

**Comment by leipero** [comment]
Just tested it with Oivaf ppa on Ubuntu (updated 9h ago at time of writing this), to my understanding it shoudl be master git? With that package, it's still the same.

**Comment by sarnex** [comment]
Go to his PPA and check the package name for your Ubuntu version, it will
have the mesa git hash in the package version.

**Comment by leipero** [comment]
This? 17.1~git1703161930.f51a32~gd~y ? I just cloned partition for testing, i don't have Ubuntu partition now.

**Comment by sarnex** [comment]
Yes, it's f51a32gd

**Comment by leipero** [comment]
Ok, it's still not fixed then for me.

**Comment by axeldavy** [comment]
When we enforce ps1.1 shaders, it works fine (else it uses 1.1 and 1.4 shaders).
I guess this is a problem with ps1.4 emulation, but couldn't find what looking at the shaders.
It is hard to debug because apitrace doesn't manage to take a trace (it has error at the start about what it thinks is invalid call -but isn't)

**Comment by axeldavy** [comment]
I found the issue.
I looked at the ps1.4 shaders used and whatever tricky they could do. Found difference in ISA generated wine vs nine. Then found mistake in nine. I'll push a patch.

**Comment by leipero** [comment]
Great, I don't know how to force 1.1 version, best i could do is to set to version 1 in winetricks (and it defaults to 1.4 i guess, or simply ignores it for nine). When you do it we can test it.

**Comment by leipero** [comment]
Not sure if should be closed, I just tested with mesa git1704130730.a981e6~gd~z (Oibaf PPA), problem is still there.

**Comment by MEXAHOTABOP** [comment]
last nine update in mesa mainline was in 27.03.2017 just wait a bit more or use mesa from this repository

**Comment by leipero** [comment]
Oh, ok, will wait and re-test and report back, couldn't do it earlier, thanks.

**Comment by MEXAHOTABOP** [comment]
and path accepted

**Comment by leipero** [comment]
Just tested on git1704151930.566f2e~gd~z, I can confirm it works fine now, thanks :).
