### ISSUE TITLE
Metro Last Light : GPU Lockup on GTX670

### ISSUE THREAD

**Issue by tizbac** [iXit/Mesa-3D#48]
Metro Last Light , causes the whole system to lockup before reaching main menu

**Comment by axeldavy** [comment]
Is it fixed with our recent patches ?

**Comment by tizbac** [comment]
No, still crashes when loading level
Il 20/gen/2015 08:33 "axeldavy" <notifications@github.com> ha scritto:

**Comment by cRaZy-bisCuiT** [comment]
Please don't get me wrong: Is it worth patching this issue since the game is availabke native for linux nowadays? I feel like the issue could get close. Except for the fix might fix other problems as well.

**Comment by axeldavy** [comment]
any issue should be fixed :-)
